#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

RPROMPT+='[%D{%L:%M:%S %p}]'

alias scp='rsync'
# alias pms='sudo pacman -S --needed'

# use it like this: run_long_command; alert
# alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" \
# "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# export EDITOR=myemacs
# export BROWSER=firefox
# . /etc/profile.d/vte.sh

# # The next line updates PATH for the Google Cloud SDK.
# if [ -f '/home/sorawee/google-cloud-sdk/path.zsh.inc' ]; then source '/home/sorawee/google-cloud-sdk/path.zsh.inc'; fi

# # The next line enables shell command completion for gcloud.
# if [ -f '/home/sorawee/google-cloud-sdk/completion.zsh.inc' ]; then source '/home/sorawee/google-cloud-sdk/completion.zsh.inc'; fi

# # OPAM configuration
# . /home/sorawee/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

unsetopt cdablevars

source ~/git/zsh-autosuggestions/zsh-autosuggestions.zsh

# opam configuration
test -r /Users/sorawee/.opam/opam-init/init.zsh && . /Users/sorawee/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

eval "$(rbenv init -)"
